### ISSUE TITLE
Exception 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by stefbontinckx** [geertmeersman/miwa#16]
I have added the integration via HACS, added it via my integrations. 
Filled in my account email and password, but when starting the integration I get the following message: 

`Exception 'NoneType' object has no attribute 'get'`

Any pointers what could cause this? 

Thanks!

**Comment by geertmeersman** [comment]
Hi Stef, probably sth you don't have access to. Can you activate debug and provideme the output of the logs? You can always reach out on Discord too, will be easier to solve it
