### ISSUE TITLE
Afvalkalender

### ISSUE THREAD

**Issue by TheAnt1dot3** [geertmeersman/miwa#75]
Hallo Geert,

Mooi werk met de integratie met my miwa!
Ik ga even meezoeken (maar beperkte tijd) of het mogelijk is om de afvalkalender ook in HASS te krijgen.
Zou handig zijn moest ik acties kunnen triggeren wanneer er HV,GFT,.. dient buiten gezet te worden.
Je ziet wel een pull request verschijnen moest het me lukken om tijd te vinden :) 

Thanks! 

Stef

**Comment by geertmeersman** [comment]
Hoi Stef, ik heb hier over nagedacht, maar langs de andere kant werkt de afhalbeheer integratie zeer goed, dus wou geen dubbel werk leveren :-)

https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/

**Comment by TheAnt1dot3** [comment]
Ow, haha nee inderdaad. Zag miwa er niet tussen staan dus dacht dat het niet compatibel was. Ik zao het eens nakijken. Thanks !

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by geertmeersman** [comment]
Configuratie voor de afvalbeheer integratie voor miwa:

```
wastecollector: recycleapp
resources:
  - restafval
  - papier
  - pmd
  - gft
  - textiel
  - snoeihout
postcode: xxxx
streetname: xxxx
streetnumber: xxxx
dutch: 1
dateonly: 1
dateformat: "%A %d %B"
upcomingsensor: 0
dateobject: 0
alwaysshowday: 0
builtinicons: 1
```
